# Generated by Django 4.2.16 on 2025-07-23 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stazione_ricarica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('available', 'Disponibile'), ('occupied', 'Occupata'), ('faulted', 'Guasta'), ('unavailable', 'Non disponibile')], default='available', max_length=20)),
                ('power_capacity', models.FloatField()),
                ('is_online', models.BooleanField(default=False)),
                ('ultimo_segnale', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sessione_ricarica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=50, unique=True)),
                ('user_id', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('energy_consumed', models.FloatField(default=0.0)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.stazione_ricarica')),
            ],
        ),
        migrations.CreateModel(
            name='OCPP_Messaggio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('call', 'Call'), ('callresult', 'CallResult'), ('callerror', 'CallError')], max_length=50)),
                ('action', models.CharField(max_length=50)),
                ('message_data', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.stazione_ricarica')),
            ],
        ),
    ]
