# Generated by Django 5.2.4 on 2025-09-05 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SNMPDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('snmp_port', models.IntegerField(default=161)),
                ('community_string', models.CharField(default='public', max_length=50)),
                ('snmp_version', models.CharField(default='2c', max_length=10)),
                ('is_reachable', models.BooleanField(default=False)),
                ('last_poll', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SNMPPollingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('oid', models.CharField(max_length=100)),
                ('metric_type', models.CharField(max_length=20)),
                ('polling_interval', models.IntegerField(default=60)),
                ('threshold_min', models.FloatField(blank=True, null=True)),
                ('threshold_max', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stazione_ricarica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('available', 'Disponibile'), ('occupied', 'Occupata'), ('faulted', 'Guasta'), ('unavailable', 'Non disponibile')], default='available', max_length=20)),
                ('power_capacity', models.FloatField()),
                ('is_online', models.BooleanField(default=False)),
                ('ultimo_segnale', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SNMPAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('voltage', 'Tensione(V)'), ('current', 'Corrente(A)'), ('power', 'Potenza(W)'), ('energy', 'Energia(kWh)'), ('temperature', 'Temperatura (°C)'), ('status', 'Stato'), ('uptime', 'Uptime'), ('network_traffic', 'Traffico di rete')], max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical'), ('emergency', 'Emergency')], max_length=50)),
                ('threshold_value', models.FloatField()),
                ('current_value', models.FloatField()),
                ('message', models.TextField()),
                ('is_solved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('risolved_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.snmpdevice')),
            ],
        ),
        migrations.AddField(
            model_name='snmpdevice',
            name='station',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stations.stazione_ricarica'),
        ),
        migrations.CreateModel(
            name='Sessione_ricarica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=50, unique=True)),
                ('user_id', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('energy_consumed', models.FloatField(default=0.0)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.stazione_ricarica')),
            ],
        ),
        migrations.CreateModel(
            name='OCPP_Messaggio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('call', 'Call'), ('callresult', 'CallResult'), ('callerror', 'CallError')], max_length=50)),
                ('action', models.CharField(max_length=50)),
                ('message_data', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.stazione_ricarica')),
            ],
        ),
        migrations.CreateModel(
            name='SNMPMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('voltage', 'Tensione(V)'), ('current', 'Corrente(A)'), ('power', 'Potenza(W)'), ('energy', 'Energia(kWh)'), ('temperature', 'Temperatura (°C)'), ('status', 'Stato'), ('uptime', 'Uptime'), ('network_traffic', 'Traffico di rete')], max_length=50)),
                ('oid', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('string_value', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.snmpdevice')),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'metric_type', 'timestamp'], name='stations_sn_device__cd2efd_idx')],
            },
        ),
    ]
