# Generated by Django 5.2.4 on 2025-07-26 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SNMPPollingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('oid', models.CharField(max_length=100)),
                ('metric_type', models.CharField(max_length=20)),
                ('polling_interval', models.IntegerField(default=60)),
                ('threshold_min', models.FloatField(blank=True, null=True)),
                ('threshold_max', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SNMPDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('snmp_port', models.IntegerField(default=161)),
                ('community_string', models.CharField(default='public', max_length=50)),
                ('snmp_version', models.CharField(default='2c', max_length=10)),
                ('is_reachable', models.BooleanField(default=False)),
                ('last_poll', models.DateTimeField(blank=True, null=True)),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stations.stazione_ricarica')),
            ],
        ),
        migrations.CreateModel(
            name='SNMPAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('voltage', 'Tensione(V)'), ('current', 'Corrente(A)'), ('power', 'Potenza(W)'), ('energy', 'Energia(kWh)'), ('temperature', 'Temperatura (°C)'), ('status', 'Stato'), ('uptime', 'Uptime'), ('network_traffic', 'Traffico di rete')], max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical'), ('emergency', 'Emergency')], max_length=50)),
                ('threshold_value', models.FloatField()),
                ('current_value', models.FloatField()),
                ('message', models.TextField()),
                ('is_solved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('risolved_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.snmpdevice')),
            ],
        ),
        migrations.CreateModel(
            name='SNMPMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('voltage', 'Tensione(V)'), ('current', 'Corrente(A)'), ('power', 'Potenza(W)'), ('energy', 'Energia(kWh)'), ('temperature', 'Temperatura (°C)'), ('status', 'Stato'), ('uptime', 'Uptime'), ('network_traffic', 'Traffico di rete')], max_length=50)),
                ('oid', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('string_value', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.snmpdevice')),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'metric_type', 'timestamp'], name='stations_sn_device__cd2efd_idx')],
            },
        ),
    ]
