# Generated by Django 5.2.4 on 2025-08-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_snmppollingconfig_snmpdevice_snmpalert_snmpmetric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stazione_ricarica',
            name='id',
        ),
        migrations.AlterField(
            model_name='stazione_ricarica',
            name='station_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
