# Generated by Django 5.2.4 on 2025-08-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_remove_stazione_ricarica_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stazione_ricarica',
            name='station_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
