# Generated by Django 5.2.4 on 2025-09-05 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerTypes',
            fields=[
                ('id', models.BigIntegerField(max_length=10, primary_key=True, serialize=False)),
                ('model', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('Tracker_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('imei', models.CharField(db_index=True, max_length=20)),
                ('plate_number', models.CharField(blank=True, db_column='plate_number', max_length=20, null=True, verbose_name='plate_number')),
                ('status', models.CharField(blank=True, max_length=32, null=True)),
                ('last_seen', models.DateTimeField(blank=True, db_column='last seen', null=True)),
                ('vin', models.CharField(blank=True, max_length=17, null=True)),
                ('station_id', models.IntegerField(blank=True, null=True)),
                ('tracker_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Tracker',
                'indexes': [models.Index(fields=['imei'], name='Tracker_imei_a3b835_idx'), models.Index(fields=['last_seen'], name='Tracker_last se_924235_idx'), models.Index(fields=['station_id'], name='Tracker_station_8305a9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Tracker_DataMap',
            fields=[
                ('id', models.BigAutoField(max_length=10, primary_key=True, serialize=False)),
                ('avl', models.IntegerField()),
                ('unita', models.FloatField()),
                ('fattore_moltiplicativo', models.FloatField(max_length=10)),
                ('trackerTypes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.trackertypes')),
            ],
        ),
        migrations.CreateModel(
            name='TrackerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(help_text='Timestamp del dato (origine dispositivo)')),
                ('priority', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('altitude', models.IntegerField(blank=True, help_text='Altitudine in metri', null=True)),
                ('angle', models.PositiveSmallIntegerField(blank=True, help_text='Angolo/direzione 0-359', null=True)),
                ('satellites', models.PositiveSmallIntegerField(blank=True, db_column='datellites', null=True)),
                ('speed', models.FloatField(blank=True, help_text='Velocità (km/h)', null=True)),
                ('event_id', models.IntegerField(blank=True, null=True)),
                ('properties_count', models.PositiveIntegerField(blank=True, null=True)),
                ('io_elements', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('km', models.DecimalField(blank=True, decimal_places=3, help_text='Chilometri totali', max_digits=12, null=True)),
                ('tracker', models.ForeignKey(db_column='Tracker_id', on_delete=django.db.models.deletion.CASCADE, related_name='data', to='tracker.tracker')),
            ],
            options={
                'db_table': 'Tracker_data',
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['tracker', 'ts'], name='Tracker_dat_Tracker_70be43_idx'), models.Index(fields=['ts'], name='Tracker_dat_ts_a6b834_idx'), models.Index(fields=['event_id'], name='Tracker_dat_event_i_2368b9_idx')],
            },
        ),
    ]
